config/routes.rb
Voteit::Application.routes.draw do
  root :to => "meetings#index"
    
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get 'login' => "sessions#new", :as => :login
  get 'logout' => "sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register

  resources :votings, :except => [:new, :create] do
    resources :vote_alternatives, :except => [:show, :index]
    get 'vote' => "votings#vote", :as => :vote
    get 'close' => "votings#close", :as => :close
    get 'open' => "votings#open", :as => :open
  end

  resources :meetings do 
    resources :votings
  end

  

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	extend FriendlyId

	friendly_id :period, :use => :slugged
	has_many :votings, :inverse_of => :meeting, :dependent => :destroy
  	attr_accessible :period
  	accepts_nested_attributes_for :votings
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authorize, :except => :index
  before_filter :authorize_admin, :except => [:index, :show]
  respond_to :html, :json

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all

    respond_with @meetings
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
    @votings = @meeting.votings

    respond_with @meeting
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_with @meeting
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_with(@meeting) do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_with(@meeting) do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_with(@meeting) do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :period %><br />
    <%= f.text_field :period %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to '← All meetings', meetings_path %>

app/views/meetings/index.html.erb
<h1>VoteIT</h1>

<% if is_loggedin? %>
<p>
  <strong>Current user:</strong> <%= current_user.nick%> |
  <%= link_to 'Log out', logout_path%><br />
  <strong>Is admin:</strong> <%= is_admin?%>
</p>

<% unless @meetings.blank? %>
<table>
  <tr>
    <th>Period</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.period %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td class="admin"><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td class="admin"><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<% else %>

<p>No meetings</p>

<% end %>

<div class="admin">
  <p>
    <%= link_to 'New Meeting', new_meeting_path %> |
    <%= link_to 'New user', new_user_path %> |
    <%= link_to 'All users', users_path %> 
  </p>
</div>

<% else %>

<%= render :template => "sessions/new" %>

<% end %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<h2>Votings for <%= @meeting.period%> meeting</h2>

<%= render :template => "votings/index" %>

<h3>New voting</h3>

<div class="admin">
<p>
	<%= link_to 'New Voting', new_meeting_voting_path(@meeting) %> | 
	<%= link_to 'Edit', edit_meeting_path(@meeting) %>
</p>
</div>

<%= link_to '← All meetings', meetings_path %>