config/routes.rb
Voteit::Application.routes.draw do
  root :to => "meetings#index"
    
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get 'login' => "sessions#new", :as => :login
  get 'logout' => "sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register

  resources :votings, :except => [:new, :create] do
    resources :vote_alternatives, :except => [:show, :index]
    get 'vote' => "votings#vote", :as => :vote
    get 'close' => "votings#close", :as => :close
    get 'open' => "votings#open", :as => :open
  end

  resources :meetings do 
    resources :votings
  end

  

end

app/models/voting.rb
class Voting < ActiveRecord::Base
	belongs_to :meeting, :inverse_of => :votings
	
	has_many :vote_alternatives, :inverse_of => :voting, :dependent => :destroy
	#has_many :user_votes
	has_many :users, :through => :user_votes

  	attr_accessible :description, :title, :meeting, :open
  	accepts_nested_attributes_for :vote_alternatives

  	validates :title, :presence => true
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  before_filter :authorize
  before_filter :authorize_admin, :except => [:index, :show, :vote]
  respond_to :html, :json

  # GET /votings
  # GET /votings.json
  def index
    @votings = Voting.all

    respond_with @votings
  end

  def vote
    @voting = Voting.find(params[:voting_id])
    @vote_alternative = @voting.vote_alternatives.find(params[:alt])
    @vote = UserVote.new(:user => current_user, :voting => @voting)
    
    if @vote.save
      @vote_alternative.update_attribute :votes, @vote_alternative.votes + 1      
    else
      flash.now.alert = @vote.error_messages_as_json
    end

    respond_with(@voting) do |format|
      format.js
      format.json { head :no_content }
      format.html { redirect_to [@voting.meeting, @voting] }
    end
  end

  def open
    @voting = Voting.find(params[:voting_id])
    @voting.update_attribute :open, true

    respond_with(@voting) do |format|
      format.html { redirect_to [@voting.meeting, @voting], :notice => "Voting opened" }
      format.json { head :no_content }
    end
  end

  def close
    @voting = Voting.find(params[:voting_id])
    @voting.update_attribute :open, false

    respond_with(@voting) do |format|
      format.html { redirect_to [@voting.meeting, @voting], :notice => "Voting closed" }
      format.json { head :no_content }
    end
  end

  # GET /votings/1
  # GET /votings/1.json
  def show
    @voting = Voting.find(params[:id])
    @alternatives = @voting.vote_alternatives.order("votes DESC")

    respond_with @voting
  end

  # GET /votings/new
  # GET /votings/new.json
  def new
    @meeting = Meeting.find(params[:meeting_id])
    @voting = @meeting.votings.build

    respond_with @voting
  end

  # GET /votings/1/edit
  def edit
    @voting = Voting.find(params[:id])
  end

  # POST /votings
  # POST /votings.json
  def create
    @meeting = Meeting.find(params[:meeting_id])
    @voting = @meeting.votings.build(params[:voting])

    respond_with(@voting) do |format|
      if @voting.save
        format.html { redirect_to @meeting, notice: 'Voting was successfully created.' }
        format.json { render json: @voting, status: :created, location: @voting }
      else
        format.html { render "new" }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votings/1
  # PUT /votings/1.json
  def update
    @voting = Voting.find(params[:id])
    @meeting = @voting.meeting

    respond_with(@voting) do |format|
      if @voting.update_attributes(params[:voting])
        format.html { redirect_to @meeting, notice: 'Voting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @voting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votings/1
  # DELETE /votings/1.json
  def destroy
    @voting = Voting.find(params[:id])
    @voting.destroy

    respond_with(@voting) do |format|
      format.html { redirect_to @voting.meeting }
      format.json { head :no_content }
    end
  end
end

app/helpers/votings_helper.rb
module VotingsHelper
end

app/views/votings/_form.html.erb
<%= form_for [@voting.meeting, @voting] do |f| %>
  <% if @voting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voting.errors.count, "error") %> prohibited this voting from being saved:</h2>

      <ul>
      <% @voting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votings/destroy.js.erb
console.log("Destroy");

app/views/votings/edit.html.erb
<h1>Editing voting</h1>

<%= render 'form' %>

<%= link_to "← #{@voting.meeting.period} meeting", meeting_path(@voting.meeting) %> | 
<%= link_to 'Show', [@voting.meeting, @voting] %>

app/views/votings/index.html.erb
<% unless @votings.blank? %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votings.each do |voting| %>
  <tr>
    <td><%= voting.title %></td>
    <td><%= voting.description %></td>
    <td><%= link_to 'Show', meeting_voting_path(voting.meeting, voting) %></td>
    <td class="admin"><%= link_to 'Edit', edit_meeting_voting_path(voting.meeting, voting) %></td>
    <td class="admin"><%= link_to 'Destroy', [voting.meeting, voting], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<% else %>

<p>No votings</p>

<% end %>

app/views/votings/new.html.erb
<h1>New voting for the '<%= @voting.meeting.period %>' meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_votings_path%>

app/views/votings/show.html.erb
<p>
  <b>Title:</b>
  <%= @voting.title %>
</p>

<p>
  <b>Description:</b>
  <%= @voting.description %>
</p>

<% unless @voting.open %>

<p>Voting is closed</p>

<% end%>

<% unless @alternatives.blank?%>
<p>
	<strong>Alternatives</strong>
</p>

<ul>
	<% @alternatives.each do |alt| %>
	<li id="alt-<%= alt.id%>">
		<h3><%= alt.title%> (<span class="alt-votes" id="alt-<%= alt.id %>-votes"><%= alt.votes%></span> votes)</h3>

		<p>
		<% if @voting.open %>
		<%= link_to 'Vote', voting_vote_path(alt.voting, :alt => alt.id), :class => "vote-btn", :remote => true %> |
		<% end %>
		<%= link_to 'Remove alternative', [@voting, alt], 
				:method => :delete, 
				:remote => true,
				:class => "admin", 
				:data => {:confirm => "Sure?"} %>
		</p>
	</li>
	<% end %>
</ul>

<% else %>

<p>No alternatives or voting is closed</p>

<% end %>

<div class="admin">
	<p>
		<%= link_to 'Add Vote alternative', new_voting_vote_alternative_path(@voting) %> | 

		<%= link_to 'Edit', edit_voting_path(@voting) %> | 

		<% if @voting.open %>
			<%= link_to 'Close voting', voting_close_path(@voting) %>
		<% else %>
			<%= link_to 'Open voting', voting_open_path(@voting) %>
		<%end%>
	</p>

</div>

<%= link_to "← #{@voting.meeting.period} meeting", meeting_path(@voting.meeting) %>

app/views/votings/vote.js.erb
<% if @vote.valid? %>
	$("#alt-<%= @vote_alternative.id%>")
		.find(".alt-votes").html("<%= @vote_alternative.votes %>");

<% else %>
	$("#notice").remove();
	
	var html = "<ul id='notice'>",
		errors = <%= @vote.error_messages_as_json.html_safe %>;

	errors.forEach(function(e) {
		html += '<li>'+ e +'</li>';
	});

	html += "</ul>";

	$("body").prepend(html);

<% end %>