config/routes.rb
Voteit::Application.routes.draw do
  root :to => "meetings#index"
    
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  get 'login' => "sessions#new", :as => :login
  get 'logout' => "sessions#destroy", :as => :logout
  get 'register' => "users#new", :as => :register

  resources :votings, :except => [:new, :create] do
    resources :vote_alternatives, :except => [:show, :index]
    get 'vote' => "votings#vote", :as => :vote
    get 'close' => "votings#close", :as => :close
    get 'open' => "votings#open", :as => :open
  end

  resources :meetings do 
    resources :votings
  end

  

end

app/models/vote_alternative.rb
class VoteAlternative < ActiveRecord::Base
	belongs_to :voting, :inverse_of => :vote_alternatives
  	attr_accessible :identifier, :title, :voting, :votes
end

app/controllers/vote_alternatives_controller.rb
class VoteAlternativesController < ApplicationController
  respond_to :html, :json, :js

  # GET /vote_alternatives
  # GET /vote_alternatives.json
  def index
    @vote_alternatives = VoteAlternative.all

    respond_with @vote_alternative
  end

  # GET /vote_alternatives/1
  # GET /vote_alternatives/1.json
  def show
    @vote_alternative = VoteAlternative.find(params[:id])

    respond_with @vote_alternative
  end

  # GET /vote_alternatives/new
  # GET /vote_alternatives/new.json
  def new
    @voting = Voting.find(params[:voting_id])
    @vote_alternative = @voting.vote_alternatives.build

    respond_with @vote_alternative
  end

  # GET /vote_alternatives/1/edit
  def edit
    @vote_alternative = VoteAlternative.find(params[:id])
  end

  # POST /vote_alternatives
  # POST /vote_alternatives.json
  def create
    @voting = Voting.find(params[:voting_id])
    @vote_alternative = @voting.vote_alternatives.build(params[:vote_alternative])

    respond_with(@vote_alternative) do |format|
      if @vote_alternative.save
        format.html { redirect_to @voting, notice: 'Vote alternative was successfully created.' }
        format.json { render json: @vote_alternative, status: :created, location: @vote_alternative }
      else
        format.html { render action: "new" }
        format.json { render json: @vote_alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vote_alternatives/1
  # PUT /vote_alternatives/1.json
  def update
    @vote_alternative = VoteAlternative.find(params[:id])
    @voting = @vote_alternative.voting

    respond_with(@vote_alternative) do |format|
      if @vote_alternative.update_attributes(params[:vote_alternative])
        format.html { redirect_to [@voting.meeting, @voting, @vote_alternative], notice: 'Vote alternative was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote_alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vote_alternatives/1
  # DELETE /vote_alternatives/1.json
  def destroy
    @vote_alternative = VoteAlternative.find(params[:id])
    @vote_alternative.destroy

    respond_with(@vote_alternative) do |format|
      format.js
      format.html { redirect_to @vote_alternative.voting }
      format.json { head :no_content }
    end
  end
end

app/helpers/vote_alternatives_helper.rb
module VoteAlternativesHelper
end

app/views/vote_alternatives/_form.html.erb
<%= form_for([@vote_alternative.voting, @vote_alternative]) do |f| %>
  <% if @vote_alternative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote_alternative.errors.count, "error") %> prohibited this vote_alternative from being saved:</h2>

      <ul>
      <% @vote_alternative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vote_alternatives/destroy.js.erb
$("#alt-<%= @vote_alternative.id %>").remove();

app/views/vote_alternatives/edit.html.erb
<h1>Editing vote_alternative</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote_alternative %> |
<%= link_to 'Back', vote_alternatives_path %>

app/views/vote_alternatives/index.html.erb
<h1>Listing vote_alternatives</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Identifier</th>
    <th>Voting</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vote_alternatives.each do |vote_alternative| %>
  <tr>
    <td><%= vote_alternative.title %></td>
    <td><%= vote_alternative.identifier %></td>
    <td><%= vote_alternative.voting_id %></td>
    <td><%= link_to 'Show', vote_alternative %></td>
    <td><%= link_to 'Edit', edit_vote_alternative_path(vote_alternative) %></td>
    <td><%= link_to 'Destroy', vote_alternative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote alternative', new_vote_alternative_path %>

app/views/vote_alternatives/new.html.erb
<h1>New vote_alternative</h1>

<%= render 'form' %>

<%= link_to 'Back', meeting_voting_path(@voting.meeting, @voting) %>

app/views/vote_alternatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @vote_alternative.title %>
</p>

<p>
  <b>Identifier:</b>
  <%= @vote_alternative.identifier %>
</p>

<p>
  <b>Voting:</b>
  <%= @vote_alternative.voting_id %>
</p>

<%= link_to 'Edit', edit_vote_alternative_path(@vote_alternative) %> |
<%= link_to 'Back', vote_alternatives_path %>